# Config for training ALAE on CelebA-HQ at resolution 256x256

NAME: celeba-hq256
DATASET:
  PART_COUNT: 16
  SIZE: 29000
  SIZE_TEST: 1000
  PATH: /data/datasets/celeba-hq/tfrecords/celeba-r%02d.tfrecords.%03d
  PATH_TEST: /data/datasets/celeba-hq-test/tfrecords/celeba-r%02d.tfrecords.%03d
  MAX_RESOLUTION_LEVEL: 8
  SAMPLES_PATH: dataset_samples/faces/realign1024x1024
  STYLE_MIX_PATH: style_mixing/test_images/set_ffhq
MODEL:
  LATENT_SPACE_SIZE: 512
  LAYER_COUNT: 7
  MAX_CHANNEL_COUNT: 512
  START_CHANNEL_COUNT: 64
  DLATENT_AVG_BETA: 0.995
  MAPPING_LAYERS: 8
OUTPUT_DIR: training_artifacts/celeba-hq256
TRAIN:
  BASE_LEARNING_RATE: 0.002
  EPOCHS_PER_LOD: 30
  LEARNING_DECAY_RATE: 0.1
  LEARNING_DECAY_STEPS: []
  TRAIN_EPOCHS: 280
  #                    4       8       16       32       64       128        256       512       1024
  LOD_2_BATCH_8GPU: [512,    256,     128,      64,      32,       32,        32,       32,        24]
  LOD_2_BATCH_4GPU: [512,    256,     128,      64,      32,       32,        32,       32,        16]
  LOD_2_BATCH_2GPU: [128,    128,     128,      64,      32,       32,        16]
  LOD_2_BATCH_1GPU: [128,    128,     128,      64,      32,       16]

  LEARNING_RATES: [0.0015,  0.0015,   0.0015,   0.0015,  0.0015,   0.0015,     0.0015,     0.003,    0.003]
