# Config for training ALAE on CelebA at resolution 128x128

NAME: celeba
PPL_CELEBA_ADJUSTMENT: True
DATASET:
  PART_COUNT: 16
  SIZE: 182637
  SIZE_TEST: 202576 - 182637
  PATH: /data/datasets/celeba/tfrecords/celeba-r%02d.tfrecords.%03d
  PATH_TEST: /data/datasets/celeba-test/tfrecords/celeba-r%02d.tfrecords.%03d
  MAX_RESOLUTION_LEVEL: 7

  SAMPLES_PATH: dataset_samples/faces/realign128x128
  STYLE_MIX_PATH: style_mixing/test_images/set_celeba
MODEL:
  LATENT_SPACE_SIZE: 256
  LAYER_COUNT: 6
  MAX_CHANNEL_COUNT: 256
  START_CHANNEL_COUNT: 64
  DLATENT_AVG_BETA: 0.995
  MAPPING_LAYERS: 8
OUTPUT_DIR: training_artifacts/celeba
TRAIN:
  BASE_LEARNING_RATE: 0.002
  EPOCHS_PER_LOD: 6
  LEARNING_DECAY_RATE: 0.1
  LEARNING_DECAY_STEPS: []
  TRAIN_EPOCHS: 80
  #                    4       8       16       32       64       128        256       512       1024
  LOD_2_BATCH_8GPU: [512,    256,     128,      64,      32,       32,        32,       32,        32]
  LOD_2_BATCH_4GPU: [512,    256,     128,      64,      32,       32,        32,       32,        16]
  LOD_2_BATCH_2GPU: [128,    128,     128,      64,      32,       32,        16]
  LOD_2_BATCH_1GPU: [128,    128,     128,      64,      32,       16]

  LEARNING_RATES: [0.0015,  0.0015,   0.0015,   0.0015,  0.0015,   0.0015,     0.002,     0.003,    0.003]
