DATASET:
  PART_COUNT: 1
  SIZE: 60000
  SIZE_TEST: 10000
  PATH: /data/datasets/mnist_fc/tfrecords/mnist-r%02d.tfrecords.%03d
  PATH_TEST: /data/datasets/mnist_fc/tfrecords/mnist_test-r%02d.tfrecords.%03d
  MAX_RESOLUTION_LEVEL: 5
  FLIP_IMAGES: False
MODEL:
  # LATENT_SPACE_SIZE: 256
  LATENT_SPACE_SIZE: 50
  LAYER_COUNT: 4
  MAX_CHANNEL_COUNT: 256
  START_CHANNEL_COUNT: 64
  DLATENT_AVG_BETA: 0.995
  # MAPPING_LAYERS: 5
  MAPPING_LAYERS: 6
  CHANNELS: 1
  GENERATOR: "GeneratorFC"
  ENCODER: "EncoderFC"
  MAPPING_D: "MappingDNoStyle"

OUTPUT_DIR: mnist_results_fc2z_2
TRAIN:
  # ADAM_BETA_0: 0.5
  # ADAM_BETA_1: 0.999
  BASE_LEARNING_RATE: 0.002
  EPOCHS_PER_LOD: 0
  LEARNING_DECAY_RATE: 0.1
  LEARNING_DECAY_STEPS: []
  TRAIN_EPOCHS: 600
  LOD_2_BATCH_8GPU: [128, 128, 128,   1024]
  LOD_2_BATCH_4GPU: [128, 128, 128,   128]
  LOD_2_BATCH_2GPU: [128, 128, 128,   128]
  LOD_2_BATCH_1GPU: [128, 128, 128,   128]

  LEARNING_RATES: [0.003,  0.003,   0.002,   0.002]

  SNAPSHOT_FREQ: [300, 300, 300, 300, 300]

  REPORT_FREQ: [100, 300, 300, 300, 300]
